name: sailspad

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.5

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  url_launcher: ^6.1.6
  google_fonts: ^3.0.1
  analyzer: ^5.0.0
  intl: ^0.17.0
  nylo_framework: ^3.4.0
  pretty_dio_logger: ^1.2.0-beta-1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  awesome_snackbar_content: ^0.0.8
  image_cropper: ^3.0.0
  image_picker: ^0.8.5+3
  font_awesome_flutter: ^10.2.1
  pin_code_fields: ^7.4.0
  dropdown_button2: ^1.8.1
  dot_navigation_bar: ^1.0.1+4
  flutter_spinkit: ^5.1.0
  modal_bottom_sheet:
   git:
     url: https://github.com/eli1stark/modal_bottom_sheet.git
     ref: main
     path: modal_bottom_sheet
  qr_flutter: ^4.0.0
  webview_flutter: ^3.0.4
  flutter_inappwebview: ^5.4.3+7
  permission_handler: ^10.0.2
  percent_indicator: ^4.2.2
  fl_chart: ^0.55.2

dev_dependencies:
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.2.9
  #  lints: ^2.0.0
  flutter_test:
    sdk: flutter

# APP ICON - public/assets/app_icon/icon.png
# Build icons: "flutter pub run flutter_launcher_icons:main"
flutter_icons:
  android: true
  ios: true
  image_path: "public/assets/app_icon/icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - public/assets/fonts/
    - public/assets/images/
    - public/assets/app_icon/
    - lang/
    - .env

  fonts:
    - family: SailspadIcons
      fonts:
        - asset: public/assets/fonts/SailspadIcons.ttf
